//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.ServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.IRequest", CallbackContract=typeof(Client.ServiceReference.IRequestCallback))]
    public interface IRequest {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRequest/SendRequest", ReplyAction="http://tempuri.org/IRequest/SendRequestResponse")]
        void SendRequest(Shared.Models.SaleDetails saleDetails);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRequest/SendRequest", ReplyAction="http://tempuri.org/IRequest/SendRequestResponse")]
        System.Threading.Tasks.Task SendRequestAsync(Shared.Models.SaleDetails saleDetails);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRequestCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IRequest/SendResponse")]
        void SendResponse(string response);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRequestChannel : Client.ServiceReference.IRequest, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RequestClient : System.ServiceModel.DuplexClientBase<Client.ServiceReference.IRequest>, Client.ServiceReference.IRequest {
        
        public RequestClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public RequestClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public RequestClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public RequestClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public RequestClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void SendRequest(Shared.Models.SaleDetails saleDetails) {
            base.Channel.SendRequest(saleDetails);
        }
        
        public System.Threading.Tasks.Task SendRequestAsync(Shared.Models.SaleDetails saleDetails) {
            return base.Channel.SendRequestAsync(saleDetails);
        }
    }
}
